<!--FORMULAIRE DE CONNEXION-->

<section class="container section-center" >
    
    <h2>Connexion</h2>
    
    
    
    <form class="form" action="index.php?action=connexion" method="POST">
        
        <?php if(isset($message)):?>
            <p class="errorMessage"><?=$message?></p>
        <?php endif; ?>
        
        
        <fieldset>
            <legend>Se connecter avec un compte utilsateur</legend>
            
             <div>
                <label for="email">E-mail</label>
                <input type="email" name="email" required/>
            </div>
            
            <div>
                <label for="password">Mot de passe</label>
                <input type="password" name="password" required/>
            </div>
            
        </fieldset>
        
        <div class="submit-contenair">
                <input class="btn-link" type="submit" name="submit" value="Se connecter"/>
                <input class="btn-link" type="reset" name="Annuler" value="Annuler"/>
        </div>
        
        
    </form>
    
</section>