<!--FORMULAIRE CREATION DE COMPTE-->

<section class="container section-center" >
    
    <h2>Création d'un compte client</h2>
    
    <form class="form" action="index.php?action=create_account" method="POST">
        
        <?php if(isset($message)):?>
            <p class="errorMessage"><?=$message?></p>
        <?php endif; ?>
        
        <fieldset>
            <legend>Identité et coordonnées</legend>
            
            <div>
                <label for="prenom">Prénom</label>
                <input type="text" name="prenom" required/>
            </div>
            
            <div>
                <label for="nom">Nom</label>
                <input type="text" name="nom" required/>
            </div>
            
            <div>
                <label for="birthdate">Date de Naissance</label>
                <input type="date" name="birthdate" required/>
            </div>
            
            <div>
                <label for="adresse">Adresse</label>
                <textarea name="adresse" required></textarea>
            </div>    
            
            <div>
                <label for="ville">Ville</label>
                <input type="text" name="ville" required/>
            </div>
            
            <div>
                <label for="codePostal">Code Postal</label>
                <input type="text" name="codePostal" required/>
            </div>
            
            <div>
                <label for="phone">Téléphone</label>
                <input type="tel" name="phone" required/>
            </div>

        </fieldset>
        
        <fieldset>
            <legend>Informations d'authentification</legend>
            
             <div>
                <label for="email">E-mail</label>
                <input type="email" name="email" required/>
            </div>
            
            <div>
                <label for="password">Mot de passe</label>
                <input type="password" name="password" required/>
            </div>
            
        </fieldset>
        
        <div class="submit-contenair">
                <input class="btn-link" type="submit" name="submit" value="Créer le Compte"/>
                <input class="btn-link" type="reset" name="Annuler" value="Annuler"/>
        </div>

    </form>
    
</section>